// src/app/contact/page.tsx
'use client';

import {
  Linkedin, Github, TwitterX, EnvelopeFill,
} from 'react-bootstrap-icons';
import { ListGroup, ListGroupItem } from 'react-bootstrap';

const Contact = () => {
  return (
    <main>
      <section>
        <h1>Contact</h1>
        <p>
          Please feel free to reach out to me on any of these platforms. Email being best.
        </p>
        <ListGroup>
          <ListGroupItem>
            <a href="mailto:josephfnevin@gmail.com">
              <EnvelopeFill />
              <span>Email</span>
            </a>
          </ListGroupItem>
          <ListGroupItem>
            <a href="https://www.linkedin.com/in/joseph-nevin-2a0b56113/">
              <Linkedin />
              <span>LinkedIn</span>
            </a>
          </ListGroupItem>
          <ListGroupItem>
            <a href="https://github.com/j0zsef">
              <Github />
              <span>GitHub</span>
            </a>
          </ListGroupItem>
          <ListGroupItem>
            <a href="https://x.com/JozsefNevin">
              <TwitterX />
              <span>Twitter</span>
            </a>
          </ListGroupItem>
        </ListGroup>
      </section>
    </main>
  );
};

export default Contact;

// pages/contact.vue
<template>
  <main>
    <div>
      <p class="pb-4">Please feel free to reach out to me on any of these platforms. Email being best.</p>
      <ul>
        <li><a href="mailto:josephfnevin@gmail.com"><Icon name="ic:round-email"/>Email</a></li>
        <li><a href="https://www.linkedin.com/in/joseph-nevin-2a0b56113/"><Icon name="uil:linkedin"/>LinkedIn</a></li>
        <li><a href="https://github.com/j0zsef"><Icon name="uil:github"/>GitHub</a></li>
        <li><a href="https://twitter.com/JozsefNevin"><Icon name="uil:twitter"/>Twitter</a></li>
      </ul>
    </div>
  </main>
</template>

<script setup>
useHead({
  title: 'Contact',
  meta: [
    { name: 'description', content: 'Joseph Nevin Contact' }
  ]
})
</script>

<script>
export default {
  name: "contact.vue"
}
</script>

<style scoped>
svg {
  position: relative;
  bottom: 1px;
  right: 1px;
}
</style>
